---
apiVersion: v1
kind: Pod
metadata:
  name: test
  labels:
    name: test
spec:
  
  containers:
    - name: test-app
      image: dimplejaiswal/test-app
      
      ports:
        - containerPort: 5000
          name: test




---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: test
  name: test
spec:
  ports:
    - port: 8080
      targetPort: 5000
  selector:
    name: test
  type: LoadBalancer
